package com.learnbridge.learn_bridge_back_end.dto;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.learnbridge.learn_bridge_back_end.converter.CustomYearMonthDeserializer;
import com.learnbridge.learn_bridge_back_end.converter.CustomYearMonthSerializer;
import com.learnbridge.learn_bridge_back_end.entity.Card;

import java.time.YearMonth;

/**
 * Data Transfer Object for card operations.
 * Supports two approaches:
 * 1. Secure approach using paymentMethodId generated by Stripe.js on frontend
 * 2. Legacy/testing approach using raw card details (not recommended for production)
 */
public class AddCardRequest {
    // Card details for display / validation only
    // NOTE: These fields should ideally not be used to send raw card data to Stripe
    // They're kept for backward compatibility and UI display purposes
    private String cardNumber;
    private String holderName;

    @JsonDeserialize(using = CustomYearMonthDeserializer.class)
    @JsonSerialize(using = CustomYearMonthSerializer.class)
    private YearMonth expireDate;

    // Secure token approach - this should be the preferred method
    // This ID is generated by Stripe.js on the frontend and represents
    // tokenized card details that can be safely sent to the backend
    private String paymentMethodId;

    private String cvc;

    // flags to guide frontend UI
    private boolean isExpired;
    private boolean isDefault;

    public AddCardRequest() {}

    // Constructor for mapping back from entity if needed
    public AddCardRequest(Card card) {
        this.cardNumber   = card.getCardNumber();
        this.holderName   = card.getHolderName();
        this.expireDate   = card.getExpireDate();
        this.isDefault    = card.isDefaultCard();
        this.paymentMethodId = card.getStripePaymentMethodId();
    }

    public String getCardNumber() {
        return cardNumber;
    }

    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    public String getHolderName() {
        return holderName;
    }

    public void setHolderName(String holderName) {
        this.holderName = holderName;
    }

    public YearMonth getExpireDate() {
        return expireDate;
    }

    public void setExpireDate(YearMonth expireDate) {
        this.expireDate = expireDate;
    }

    public String getPaymentMethodId() {
        return paymentMethodId;
    }

    public void setPaymentMethodId(String paymentMethodId) {
        this.paymentMethodId = paymentMethodId;
    }

    public boolean isExpired() {
        return isExpired;
    }

    public void setExpired(boolean expired) {
        isExpired = expired;
    }

    public boolean isDefault() {
        return isDefault;
    }

    public void setDefault(boolean aDefault) {
        isDefault = aDefault;
    }

    public String getCvc() {
        return cvc;
    }

    public void setCvc(String cvc) {
        this.cvc = cvc;
    }

    @Override
    public String toString() {
        return "AddCardRequest{" +
                "cardNumber='" + (cardNumber != null ? "****" + cardNumber.substring(Math.max(0, cardNumber.length() - 4)) : null) + '\'' +
                ", holderName='" + holderName + '\'' +
                ", expireDate=" + expireDate +
                ", paymentMethodId='" + (paymentMethodId != null ? "[FILTERED]" : null) + '\'' +
                ", isExpired=" + isExpired +
                ", isDefault=" + isDefault +
                '}';
    }

    /**
     * Check if this request contains a payment method ID (preferred approach)
     */
    public boolean hasPaymentMethodId() {
        return paymentMethodId != null && !paymentMethodId.isEmpty();
    }

    /**
     * Check if this request contains raw card details (legacy approach)
     */
    public boolean hasRawCardDetails() {
        return cardNumber != null && !cardNumber.isEmpty()
                && expireDate != null
                && cvc != null && !cvc.isEmpty();
    }
}